name: PrivateIPs Check

on:
  pull_request:
    branches:
      - master
    paths:
      - "net/*.sls"
  workflow_dispatch:

env:
  GH_PR_BASE_REF: ${{ github.event.pull_request.base.sha }}
  GH_PR_HEAD_REF: ${{ github.sha }}

jobs:
  check-for-privateIPs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install needed packages
        run: |
          sudo apt update && sudo apt install python3 && sudo apt -y install python3-yaml

      - name: set files changed env variable
        run: echo "FILES_CHANGED=$(git diff --name-only ${GH_PR_BASE_REF} ${{ GH_PR_HEAD_REF }} | grep -w net | xargs)" >> $GITHUB_ENV
        shell: bash

      - name:  checkout master version of files and create diff containing ip adds and deletions for each changed file
        run: |
          for file in $FILES_CHANGED; do
            git show ${GH_PR_BASE_REF}:$file > $file.master
            git diff ${GH_PR_BASE_REF} ${GH_PR_HEAD_REF} --unified=0 -- $file > $file.gitdiff
          done

      - name: Run check scripts
        run: |
          echo "Files changed: $FILES_CHANGED"
          for file in $FILES_CHANGED; do
            ${GITHUB_WORKSPACE}/.github/scan_for_priv_ip_master.py $file
            echo -e "\n**********Checking for Private IP addresses in diff of this file in Pull Request. **********\n" 
            ${GITHUB_WORKSPACE}/.github/detect_privateip_pr.py $file
          done
        shell: bash
